--- 
javascripts: 
- base: 
  - menu
  - slider
  - jquery.jcarousel.pack
  - ifsafari
stylesheets:
- all:
  - all
- lightbox:
  - lightbox
- index:
  - index
- base:
  - menu
  - jquery.jcarousel
  - skin   